[package]
name = "idroid"
version = "0.1.0"
authors = ["li jinlei <grenlight@icloud.com>"]
edition = "2018"

[lib]
name = "idroid"

crate-type = ["rlib", "staticlib"]
# [target.'cfg(target_os = "android")'.lib]
# crate-type = ["cdylib"]

[features]
default = ["metal"]
metal = ["wgpu/metal"]
dx11 = ["wgpu/dx11"]
dx12 = ["wgpu/dx12"]
vulkan = ["wgpu/vulkan"]

[dependencies]
libc = "*"
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs", rev = "b7d8d8fa995964315318e67f4296a52d4490d518"  }

uni-view = { path="uni-view" }

nalgebra-glm = "*"
image = "0.22.1"
env_logger = "0.5"
log = "0.4"
failure = "0.1"
lazy_static = "*"

[target.'cfg(any(target_os = "macos", target_os = "windows", target_os = "linux"))'.dependencies]
shaderc = "0.6.1"
objc = "*"
winit = "0.20.0-alpha3"
raw-window-handle = "0.1"

[build-dependencies]
shaderc = "0.6.1"
sdf-generator = { path = "sdf-generator"}

[dev-dependencies]
env_logger = "0.5"
lazy_static = "*"
palette = "0.4"
rand = "0.6"

[patch.crates-io]
wgpu-native = { git = "https://github.com/gfx-rs/wgpu", version = "0.3.3", rev = "27af484f6c730e7277039b3c9664f1fe29912138", features = ["local", "metal-auto-capture"] }

