[package]
name = "sdf-text-view"
version = "0.1.0"
authors = ["li jinlei <grenlight@icloud.com>"]
edition = "2018"

[lib]
crate-type = ["rlib", "staticlib"]
# [target.'cfg(target_os = "android")'.lib]
# crate-type = ["cdylib"]

[features]
default = []

[dependencies]
libc = "*"
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs", rev = "433ab156eaa6964e0037cb5202be4dd82790422a"  }
uni-view = { path="../idroid/uni-view" }
idroid = { path="../idroid/idroid" }
# uni-view = { git = "https://github.com/grenlight/idroid", rev = "81bda67e35551898ddca1c5a9c3b6dfe209f3ffd" }
# idroid = { git = "https://github.com/grenlight/idroid", rev = "81bda67e35551898ddca1c5a9c3b6dfe209f3ffd" }

nalgebra-glm = "*"
image = "0.22.1"
env_logger = "0.5"
log = "0.4"
failure = "0.1"
lazy_static = "*"

[target.'cfg(any(target_os = "macos", target_os = "windows", target_os = "linux"))'.dependencies]
shaderc = "0.6.1"
objc = "*"
winit = "0.20.0-alpha3"
raw-window-handle = "0.1"

[build-dependencies]
shaderc = "0.6.1"

[dev-dependencies]
env_logger = "0.5"
lazy_static = "*"
palette = "0.4"
rand = "0.6"

# [patch.crates-io]
# # wgpu-native = { git = "https://github.com/gfx-rs/wgpu", rev = "a2956c0d425413796dcaa14b67c756a46f021bd2", features = ["local", "metal-auto-capture"] }
# # gfx-backend-vulkan = { path = "../my_forks/hal-0.3-fork/src/backend/vulkan"}
# # gfx-hal = { path = "../my_forks/hal-0.3-fork/src/hal"}
# gfx-backend-vulkan = { git = "https://github.com/gfx-rs/gfx", branch = "hal-0.3", rev = "143848c1c3a8ed2af9f6ed333bfab9e8ed0017ae" }
# gfx-hal = { git = "https://github.com/gfx-rs/gfx", branch = "hal-0.3", rev = "143848c1c3a8ed2af9f6ed333bfab9e8ed0017ae"}
