[package]
name = "sdf-text-view"
version = "0.1.0"
authors = ["li jinlei <grenlight@icloud.com>"]
edition = "2018"

[lib]
crate-type = ["rlib", "staticlib"]
# [target.'cfg(target_os = "android")'.lib]
# crate-type = ["cdylib"]

[features]
default = []

[dependencies]
libc = "*"
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs", rev = "cbdd74fb408d87c04423bd375806b3b6c1be1bb0"  }
# wgpu = { path = "../../wgpu-rs" }
# uni-view = { path="../idroid/uni-view" }
# idroid = { path="../idroid/idroid" }
uni-view = { git = "https://github.com/grenlight/idroid", rev = "0255499d7a913476559ebc89253a7d14494b359a" }
idroid = { git = "https://github.com/grenlight/idroid", rev = "0255499d7a913476559ebc89253a7d14494b359a" }

nalgebra-glm = "*"
image = "0.22.1"
env_logger = "0.5"
log = "0.4"
failure = "0.1"
lazy_static = "*"

[target.'cfg(any(target_os = "macos", target_os = "windows", target_os = "linux"))'.dependencies]
shaderc = "0.6.1"
objc = "*"
winit = "0.20.0-alpha4"
raw-window-handle = "0.3"

[build-dependencies]
shaderc = "0.6.1"

[dev-dependencies]
env_logger = "0.5"
lazy_static = "*"
palette = "0.4"
rand = "0.6"

# [patch.crates-io]
# wgpu-native = { git = "https://github.com/gfx-rs/wgpu", rev = "499bf1d2686ad25b5a5133d6433e4f4c9179ff0b", features = ["local", "metal-auto-capture"] }
# # gfx-backend-vulkan = { path = "../my_forks/hal-0.3-fork/src/backend/vulkan"}
# # gfx-hal = { path = "../my_forks/hal-0.3-fork/src/hal"}
# gfx-backend-vulkan = { git = "https://github.com/gfx-rs/gfx", branch = "hal-0.3", rev = "143848c1c3a8ed2af9f6ed333bfab9e8ed0017ae" }
# gfx-hal = { git = "https://github.com/gfx-rs/gfx", branch = "hal-0.3", rev = "143848c1c3a8ed2af9f6ed333bfab9e8ed0017ae"}
